global:
  domain: c-4e4de85.stage.kyma.ondemand.com
  imagePullSecret:
    name: tech-user-docker
srv:
  bindings:
    auth:
      serviceInstanceName: xsuaa
    service-manager:
      serviceInstanceName: service-manager
  image:
    repository: <your-container-registry>/bookshop-srv
    tag: latest
  resources:
    limits:
      ephemeral-storage: 1G
      memory: 500M
    requests:
      ephemeral-storage: 1G
      cpu: 500m
      memory: 500M
  health:
    liveness:
      path: /
    readiness:
      path: /
approuter:
  bindings:
    auth:
      serviceInstanceName: xsuaa
  image:
    repository: <your-container-registry>/bookshop-approuter
    tag: latest
  resources:
    limits:
      ephemeral-storage: 1G
      memory: 500M
    requests:
      ephemeral-storage: 1G
      cpu: 500m
      memory: 500M
  health:
    liveness:
      path: /
    readiness:
      path: /
  envFrom:
    - configMapRef:
        name: "{{ .Release.Name }}-approuter-configmap"
xsuaa:
  serviceOfferingName: xsuaa
  servicePlanName: application
  parameters:
    xsappname: bookshop-037
    tenant-mode: shared
    oauth2-configuration:
      redirect-uris:
        - https://*.c-4e4de85.stage.kyma.ondemand.com/**
backendDestinations:
  srv-api:
    service: srv
  mtx-api:
    service: sidecar
service-manager:
  serviceOfferingName: service-manager
  servicePlanName: container
saas-registry:
  serviceOfferingName: saas-registry
  servicePlanName: application
  parametersFrom:
    - secretKeyRef:
        name: "{{ .Release.Name }}-saas-registry-secret"
        key: parameters
saasRegistryParameters:
  xsappname: bookshop-037
  appName: bookshop-037
  displayName: bookshop-037
  description: A simple self-contained bookshop service.
  category: "CAP Application"
  bindSidecar: true
  appUrls:
    getDependencies: "/-/cds/saas-provisioning/dependencies"
    onSubscription: "/-/cds/saas-provisioning/tenant/{tenantId}"
    onSubscriptionAsync: true
    onUnSubscriptionAsync: true
    onUpdateDependenciesAsync: true
    callbackTimeoutMillis: 300000
sidecar:
  bindings:
    auth:
      serviceInstanceName: xsuaa
    saas-registry:
      serviceInstanceName: saas-registry
    service-manager:
      serviceInstanceName: service-manager
  image:
    repository: <your-container-registry>/bookshop-sidecar
    tag: latest
  resources:
    limits:
      ephemeral-storage: 1G
      memory: 500M
    requests:
      ephemeral-storage: 1G
      cpu: 500m
      memory: 500M
  health:
    liveness:
      path: /
    readiness:
      path: /
  envFrom:
    - configMapRef:
        name: "{{ .Release.Name }}-mtxs-configmap"
